<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE phrases [
    <!ELEMENT phrases (phrase*)>

    <!ELEMENT phrase (#PCDATA)>
    <!ATTLIST phrase lang CDATA "en">
    <!ATTLIST phrase src CDATA #IMPLIED>
]>
<phrases>

    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/84/pg84-images.html">I am by birth a
        Genevese, and my family is one of the most distinguished of that republic. My ancestors had
        been for many years counsellors and syndics, and my father had filled several public
        situations with honour and reputation. He was respected by all who knew him for his
        integrity and indefatigable attention to public business. He passed his younger days
        perpetually occupied by the affairs of his country; a variety of circumstances had prevented
        his marrying early, nor was it until the decline of life that he became a husband and the
        father of a family. As the circumstances of his marriage illustrate his character, I cannot
        refrain from relating them. One of his most intimate friends was a merchant who, from a
        flourishing state, fell, through numerous mischances, into poverty. This man, whose name was
        Beaufort, was of a proud and unbending disposition and could not bear to live in poverty and
        oblivion in the same country where he had formerly been distinguished for his rank and
        magnificence. Having paid his debts, therefore, in the most honourable manner, he retreated
        with his daughter to the town of Lucerne, where he lived unknown and in wretchedness. My
        father loved Beaufort with the truest friendship and was deeply grieved by his retreat in
        these unfortunate circumstances. He bitterly deplored the false pride which led his friend
        to a conduct so little worthy of the affection that united them. He lost no time in
        endeavouring to seek him out, with the hope of persuading him to begin the world again
        through his credit and assistance. </phrase>

    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/84/pg84-images.html">We were brought
        up together; there was not quite a year difference in our ages. I need not say that we were
        strangers to any species of disunion or dispute. Harmony was the soul of our companionship,
        and the diversity and contrast that subsisted in our characters drew us nearer together.
        Elizabeth was of a calmer and more concentrated disposition; but, with all my ardour, I was
        capable of a more intense application and was more deeply smitten with the thirst for
        knowledge. She busied herself with following the aerial creations of the poets; and in the
        majestic and wondrous scenes which surrounded our Swiss home —the sublime shapes of the
        mountains, the changes of the seasons, tempest and calm, the silence of winter, and the life
        and turbulence of our Alpine summers—she found ample scope for admiration and delight. While
        my companion contemplated with a serious and satisfied spirit the magnificent appearances of
        things, I delighted in investigating their causes. The world was to me a secret which I
        desired to divine. Curiosity, earnest research to learn the hidden laws of nature, gladness
        akin to rapture, as they were unfolded to me, are among the earliest sensations I can
        remember. </phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/84/pg84-images.html">We passed a few
        sad hours until eleven o'clock, when the trial was to commence. My father and the rest of
        the family being obliged to attend as witnesses, I accompanied them to the court. During the
        whole of this wretched mockery of justice I suffered living torture. It was to be decided
        whether the result of my curiosity and lawless devices would cause the death of two of my
        fellow beings: one a smiling babe full of innocence and joy, the other far more dreadfully
        murdered, with every aggravation of infamy that could make the murder memorable in horror.
        Justine also was a girl of merit and possessed qualities which promised to render her life
        happy; now all was to be obliterated in an ignominious grave, and I the cause! A thousand
        times rather would I have confessed myself guilty of the crime ascribed to Justine, but I
        was absent when it was committed, and such a declaration would have been considered as the
        ravings of a madman and would not have exculpated her who suffered through me. The
        appearance of Justine was calm. She was dressed in mourning, and her countenance, always
        engaging, was rendered, by the solemnity of her feelings, exquisitely beautiful. Yet she
        appeared confident in innocence and did not tremble, although gazed on and execrated by
        thousands, for all the kindness which her beauty might otherwise have excited was
        obliterated in the minds of the spectators by the imagination of the enormity she was
        supposed to have committed. She was tranquil, yet her tranquillity was evidently
        constrained; and as her confusion had before been adduced as a proof of her guilt, she
        worked up her mind to an appearance of courage. When she entered the court she threw her
        eyes round it and quickly discovered where we were seated. A tear seemed to dim her eye when
        she saw us, but she quickly recovered herself, and a look of sorrowful affection seemed to
        attest her utter guiltlessness. </phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/84/pg84-images.html">A murmur of
        approbation followed Elizabeth's simple and powerful appeal, but it was excited by her
        generous interference, and not in favour of poor Justine, on whom the public indignation was
        turned with renewed violence, charging her with the blackest ingratitude. She herself wept
        as Elizabeth spoke, but she did not answer. My own agitation and anguish was extreme during
        the whole trial. I believed in her innocence; I knew it. Could the dæmon who had (I did not
        for a minute doubt) murdered my brother also in his hellish sport have betrayed the innocent
        to death and ignominy? I could not sustain the horror of my situation, and when I perceived
        that the popular voice and the countenances of the judges had already condemned my unhappy
        victim, I rushed out of the court in agony. The tortures of the accused did not equal mine;
        she was sustained by innocence, but the fangs of remorse tore my bosom and would not forgo
        their hold. I passed a night of unmingled wretchedness. In the morning I went to the court;
        my lips and throat were parched. I dared not ask the fatal question, but I was known, and
        the officer guessed the cause of my visit. The ballots had been thrown; they were all black,
        and Justine was condemned. </phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/84/pg84-images.html">I spent the
        following day roaming through the valley. I stood beside the sources of the Arveiron, which
        take their rise in a glacier, that with slow pace is advancing down from the summit of the
        hills to barricade the valley. The abrupt sides of vast mountains were before me; the icy
        wall of the glacier overhung me; a few shattered pines were scattered around; and the solemn
        silence of this glorious presence-chamber of imperial Nature was broken only by the brawling
        waves or the fall of some vast fragment, the thunder sound of the avalanche or the cracking,
        reverberated along the mountains, of the accumulated ice, which, through the silent working
        of immutable laws, was ever and anon rent and torn, as if it had been but a plaything in
        their hands. These sublime and magnificent scenes afforded me the greatest consolation that
        I was capable of receiving. They elevated me from all littleness of feeling, and although
        they did not remove my grief, they subdued and tranquillised it. In some degree, also, they
        diverted my mind from the thoughts over which it had brooded for the last month. I retired
        to rest at night; my slumbers, as it were, waited on and ministered to by the assemblance of
        grand shapes which I had contemplated during the day. They congregated round me; the
        unstained snowy mountain-top, the glittering pinnacle, the pine woods, and ragged bare
        ravine, the eagle, soaring amidst the clouds—they all gathered round me and bade me be at
        peace. </phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/84/pg84-images.html">On examining my
        dwelling, I found that one of the windows of the cottage had formerly occupied a part of it,
        but the panes had been filled up with wood. In one of these was a small and almost
        imperceptible chink through which the eye could just penetrate. Through this crevice a small
        room was visible, whitewashed and clean but very bare of furniture. In one corner, near a
        small fire, sat an old man, leaning his head on his hands in a disconsolate attitude. The
        young girl was occupied in arranging the cottage; but presently she took something out of a
        drawer, which employed her hands, and she sat down beside the old man, who, taking up an
        instrument, began to play and to produce sounds sweeter than the voice of the thrush or the
        nightingale. It was a lovely sight, even to me, poor wretch who had never beheld aught
        beautiful before. The silver hair and benevolent countenance of the aged cottager won my
        reverence, while the gentle manners of the girl enticed my love. He played a sweet mournful
        air which I perceived drew tears from the eyes of his amiable companion, of which the old
        man took no notice, until she sobbed audibly; he then pronounced a few sounds, and the fair
        creature, leaving her work, knelt at his feet. He raised her and smiled with such kindness
        and affection that I felt sensations of a peculiar and overpowering nature; they were a
        mixture of pain and pleasure, such as I had never before experienced, either from hunger or
        cold, warmth or food; and I withdrew from the window, unable to bear these emotions. </phrase>

    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/1342/pg1342-images.html">Elizabeth
        listened in silence, but was not convinced: their behaviour at the assembly had not been
        calculated to please in general; and with more quickness of observation and less pliancy of
        temper than her sister, and with a judgment, too, unassailed by any attention to herself,
        she was very little disposed to approve them. They were, in fact, very fine ladies; not
        deficient in good-humour when they were pleased, nor in the power of being agreeable where
        they chose it; but proud and conceited. They were rather handsome; had been educated in one
        of the first private seminaries in town; had a fortune of twenty thousand pounds; were in
        the habit of spending more than they ought, and of associating with people of rank; and
        were, therefore, in every respect entitled to think well of themselves and meanly of others.
        They were of a respectable family in the north of England; a circumstance more deeply
        impressed on their memories than that their brother's fortune and their own had been
        acquired by trade. Mr. Bingley inherited property to the amount of nearly a hundred thousand
        pounds from his father, who had intended to purchase an estate, but did not live to do it.
        Mr. Bingley intended it likewise, and sometimes made choice of his county; but, as he was
        now provided with a good house and the liberty of a manor, it was doubtful to many of those
        who best knew the easiness of his temper, whether he might not spend the remainder of his
        days at Netherfield, and leave the next generation to purchase.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/1342/pg1342-images.html">The village
        of Longbourn was only one mile from Meryton; a most convenient distance for the young
        ladies, who were usually tempted thither three or four times a week, to pay their duty to
        their aunt, and to a milliner's shop just over the way. The two youngest of the family,
        Catherine and Lydia, were particularly frequent in these attentions: their minds were more
        vacant than their sisters', and when nothing better offered, a walk to Meryton was necessary
        to amuse their morning hours and furnish conversation for the evening; and, however bare of
        news the country in general might be, they always contrived to learn some from their aunt.
        At present, indeed, they were well supplied both with news and happiness by the recent
        arrival of a militia regiment in the neighbourhood; it was to remain the whole winter, and
        Meryton was the head-quarters. Their visits to Mrs. Philips were now productive of the most
        interesting intelligence. Every day added something to their knowledge of the officers'
        names and connections. Their lodgings were not long a secret, and at length they began to
        know the officers themselves. Mr. Philips visited them all, and this opened to his nieces a
        source of felicity unknown before. They could talk of nothing but officers; and Mr.
        Bingley's large fortune, the mention of which gave animation to their mother, was worthless
        in their eyes when opposed to the regimentals of an ensign.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/1342/pg1342-images.html">She was
        shown into the breakfast parlour, where all but Jane were assembled, and where her
        appearance created a great deal of surprise. That she should have walked three miles so
        early in the day in such dirty weather, and by herself, was almost incredible to Mrs. Hurst
        and Miss Bingley; and Elizabeth was convinced that they held her in contempt for it. She was
        received, however, very politely by them; and in their brother's manners there was something
        better than politeness—there was good-humour and kindness. Mr. Darcy said very little, and
        Mr. Hurst nothing at all. The former was divided between admiration of the brilliancy which
        exercise had given to her complexion and doubt as to the occasion's justifying her coming so
        far alone. The latter was thinking only of his breakfast. Her inquiries after her sister
        were not very favourably answered. Miss Bennet had slept ill, and though up, was very
        feverish, and not well enough to leave her room. Elizabeth was glad to be taken to her
        immediately; and Jane, who had only been withheld by the fear of giving alarm or
        inconvenience, from expressing in her note how much she longed for such a visit, was
        delighted at her entrance. She was not equal, however, to much conversation; and when Miss
        Bingley left them together, could attempt little beside expressions of gratitude for the
        extraordinary kindness she was treated with. Elizabeth silently attended her.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/1342/pg1342-images.html">Their
        brother, indeed, was the only one of the party whom she could regard with any complacency.
        His anxiety for Jane was evident, and his attentions to herself most pleasing; and they
        prevented her feeling herself so much an intruder as she believed she was considered by the
        others. She had very little notice from any but him. Miss Bingley was engrossed by Mr.
        Darcy, her sister scarcely less so; and as for Mr. Hurst, by whom Elizabeth sat, he was an
        indolent man, who lived only to eat, drink, and play at cards, who, when he found her prefer
        a plain dish to a ragout, had nothing to say to her. When dinner was over, she returned
        directly to Jane, and Miss Bingley began abusing her as soon as she was out of the room. Her
        manners were pronounced to be very bad indeed,—a mixture of pride and impertinence: she had
        no conversation, no style, no taste, no beauty. Mrs. Hurst thought the same, and added,—
        "She has nothing, in short, to recommend her, but being an excellent walker. I shall never
        forget her appearance this morning. She really looked almost wild."</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/1342/pg1342-images.html">Darcy only
        smiled; and the general pause which ensued made Elizabeth tremble lest her mother should be
        exposing herself again. She longed to speak, but could think of nothing to say; and after a
        short silence Mrs. Bennet began repeating her thanks to Mr. Bingley for his kindness to
        Jane, with an apology for troubling him also with Lizzy. Mr. Bingley was unaffectedly civil
        in his answer, and forced his younger sister to be civil also, and say what the occasion
        required. She performed her part, indeed, without much graciousness, but Mrs. Bennet was
        satisfied, and soon afterwards ordered her carriage. Upon this signal, the youngest of her
        daughters put herself forward. The two girls had been whispering to each other during the
        whole visit; and the result of it was, that the youngest should tax Mr. Bingley with having
        promised on his first coming into the country to give a ball at Netherfield. Lydia was a
        stout, well-grown girl of fifteen, with a fine complexion and good-humoured countenance; a
        favourite with her mother, whose affection had brought her into public at an early age. She
        had high animal spirits, and a sort of natural self-consequence, which the attentions of the
        officers, to whom her uncle's good dinners and her own easy manners recommended her, had
        increased into assurance. She was very equal, therefore, to address Mr. Bingley on the
        subject of the ball, and abruptly reminded him of his promise; adding, that it would be the
        most shameful thing in the world if he did not keep it. His answer to this sudden attack was
        delightful to her mother's ear.</phrase>

    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/2701/pg2701.txt">Call me Ishmael.
        Some years ago—never mind how long precisely—having little or no money in my purse, and
        nothing particular to interest me on shore, I thought I would sail about a little and see
        the watery part of the world. It is a way I have of driving off the spleen and regulating
        the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp,
        drizzly November in my soul; whenever I find myself involuntarily pausing before coffin
        warehouses, and bringing up the rear of every funeral I meet; and especially whenever my
        hypos get such an upper hand of me, that it requires a strong moral principle to prevent me
        from deliberately stepping into the street, and methodically knocking people's hats
        off—then, I account it high time to get to sea as soon as I can. This is my substitute for
        pistol and ball. With a philosophical flourish Cato throws himself upon his sword; I quietly
        take to the ship. There is nothing surprising in this. If they but knew it, almost all men
        in their degree, some time or other, cherish very nearly the same feelings towards the ocean
        with me.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/2701/pg2701.txt">Now, when I say
        that I am in the habit of going to sea whenever I begin to grow hazy about the eyes, and
        begin to be over conscious of my lungs, I do not mean to have it inferred that I ever go to
        sea as a passenger. For to go as a passenger you must needs have a purse, and a purse is but
        a rag unless you have something in it. Besides, passengers get sea-sick—grow
        quarrelsome—don't sleep of nights—do not enjoy themselves much, as a general thing;—no, I
        never go as a passenger; nor, though I am something of a salt, do I ever go to sea as a
        Commodore, or a Captain, or a Cook. I abandon the glory and distinction of such offices to
        those who like them. For my part, I abominate all honorable respectable toils, trials, and
        tribulations of every kind whatsoever. It is quite as much as I can do to take care of
        myself, without taking care of ships, barques, brigs, schooners, and what not. And as for
        going as cook,—though I confess there is considerable glory in that, a cook being a sort of
        officer on ship-board—yet, somehow, I never fancied broiling fowls;—though once broiled,
        judiciously buttered, and judgmatically salted and peppered, there is no one who will speak
        more respectfully, not to say reverentially, of a broiled fowl than I will. It is out of the
        idolatrous dotings of the old Egyptians upon broiled ibis and roasted river horse, that you
        see the mummies of those creatures in their huge bake-houses the pyramids.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/2701/pg2701.txt">I observed,
        however, that one of them held somewhat aloof, and though he seemed desirous not to spoil
        the hilarity of his shipmates by his own sober face, yet upon the whole he refrained from
        making as much noise as the rest. This man interested me at once; and since the sea-gods had
        ordained that he should soon become my shipmate (though but a sleeping-partner one, so far
        as this narrative is concerned), I will here venture upon a little description of him. He
        stood full six feet in height, with noble shoulders, and a chest like a coffer-dam. I have
        seldom seen such brawn in a man. His face was deeply brown and burnt, making his white teeth
        dazzling by the contrast; while in the deep shadows of his eyes floated some reminiscences
        that did not seem to give him much joy. His voice at once announced that he was a
        Southerner, and from his fine stature, I thought he must be one of those tall mountaineers
        from the Alleghanian Ridge in Virginia. When the revelry of his companions had mounted to
        its height, this man slipped away unobserved, and I saw no more of him till he became my
        comrade on the sea. In a few minutes, however, he was missed by his shipmates, and being, it
        seems, for some reason a huge favourite with them, they raised a cry of "Bulkington!
        Bulkington! where's Bulkington?" and darted out of the house in pursuit of him. It was now
        about nine o'clock, and the room seeming almost supernaturally quiet after these orgies, I
        began to congratulate myself upon a little plan that had occurred to me just previous to the
        entrance of the seamen.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/2701/pg2701.txt">I lay there
        dismally calculating that sixteen entire hours must elapse before I could hope for a
        resurrection. Sixteen hours in bed! the small of my back ached to think of it. And it was so
        light too; the sun shining in at the window, and a great rattling of coaches in the streets,
        and the sound of gay voices all over the house. I felt worse and worse—at last I got up,
        dressed, and softly going down in my stockinged feet, sought out my stepmother, and suddenly
        threw myself at her feet, beseeching her as a particular favour to give me a good slippering
        for my misbehaviour; anything indeed but condemning me to lie abed such an unendurable
        length of time. But she was the best and most conscientious of stepmothers, and back I had
        to go to my room. For several hours I lay there broad awake, feeling a great deal worse than
        I have ever done since, even from the greatest subsequent misfortunes. At last I must have
        fallen into a troubled nightmare of a doze; and slowly waking from it—half steeped in
        dreams—I opened my eyes, and the before sun-lit room was now wrapped in outer darkness.
        Instantly I felt a shock running through all my frame; nothing was to be seen, and nothing
        was to be heard; but a supernatural hand seemed placed in mine. My arm hung over the
        counterpane, and the nameless, unimaginable, silent form or phantom, to which the hand
        belonged, seemed closely seated by my bed-side. For what seemed ages piled on ages, I lay
        there, frozen with the most awful fears, not daring to drag away my hand; yet ever thinking
        that if I could but stir it one single inch, the horrid spell would be broken. I knew not
        how this consciousness at last glided away from me; but waking in the morning, I
        shudderingly remembered it all, and for days and weeks and months afterwards I lost myself
        in confounding attempts to explain the mystery. Nay, to this very hour, I often puzzle
        myself with it.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/2701/pg2701.txt">In what census of
        living creatures, the dead of mankind are included; why it is that a universal proverb says
        of them, that they tell no tales, though containing more secrets than the Goodwin Sands; how
        it is that to his name who yesterday departed for the other world, we prefix so significant
        and infidel a word, and yet do not thus entitle him, if he but embarks for the remotest
        Indies of this living earth; why the Life Insurance Companies pay death-forfeitures upon
        immortals; in what eternal, unstirring paralysis, and deadly, hopeless trance, yet lies
        antique Adam who died sixty round centuries ago; how it is that we still refuse to be
        comforted for those who we nevertheless maintain are dwelling in unspeakable bliss; why all
        the living so strive to hush all the dead; wherefore but the rumor of a knocking in a tomb
        will terrify a whole city. All these things are not without their meanings. But Faith, like
        a jackal, feeds among the tombs, and even from these dead doubts she gathers her most vital
        hope.</phrase>

    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/2160/pg2160.txt">The pills are good
        for nothing—I might as well swallow snowballs to cool my reins—I have told you over and over
        how hard I am to move; and at this time of day, I ought to know something of my own
        constitution. Why will you be so positive? Prithee send me another prescription—I am as lame
        and as much tortured in all my limbs as if I was broke upon the wheel: indeed, I am equally
        distressed in mind and body—As if I had not plagues enough of my own, those children of my
        sister are left me for a perpetual source of vexation—what business have people to get
        children to plague their neighbours? A ridiculous incident that happened yesterday to my
        niece Liddy, has disordered me in such a manner, that I expect to be laid up with another
        fit of the gout—perhaps, I may explain myself in my next. I shall set out tomorrow morning
        for the Hot Well at Bristol, where I am afraid I shall stay longer than I could wish. On the
        receipt of this send Williams thither with my saddle-horse and the demi pique. Tell Barns to
        thresh out the two old ricks, and send the corn to market, and sell it off to the poor at a
        shilling a bushel under market price.—I have received a snivelling letter from Griffin,
        offering to make a public submission and pay costs. I want none of his submissions, neither
        will I pocket any of his money. The fellow is a bad neighbour, and I desire, to have nothing
        to do with him: but as he is purse-proud, he shall pay for his insolence: let him give five
        pounds to the poor of the parish, and I will withdraw my action; and in the mean time you
        may tell Prig to stop proceedings.—Let Morgan's widow have the Alderney cow, and forty
        shillings to clothe her children: but don't say a syllable of the matter to any living
        soul—I'll make her pay when she is able. I desire you will lock up all my drawers, and keep
        the keys till meeting; and be sure you take the iron chest with my papers into your own
        custody—Forgive all, this trouble from, Dear Lewis, Your affectionate M. BRAMBLE GLOUCESTER,
        April 2.</phrase>
    <phrase lang="en" src="https://www.gutenberg.org/cache/epub/2160/pg2160.txt">Having no mother of
        my own, I hope you will give me leave to disburden my poor heart to you, who have always
        acted the part of a kind parent to me, ever since I was put under your care. Indeed, and
        indeed, my worthy governess may believe me, when I assure her, that I never harboured a
        thought that was otherwise than virtuous; and, if God will give me grace, I shall never
        behave so as to cast a reflection on the care you have taken in my education. I confess I
        have given just cause of offence by my want of prudence and experience. I ought not to have
        listened to what the young man said; and it was my duty to have told you all that passed,
        but I was ashamed to mention it; and then he behaved so modest and respectful, and seemed to